#Tuned for linux
# tar files
- "*.tar"
- "**/*.tar"
- "*.tar.gz"
- "**/*.tar.gz"
- "*.tgz"
- "**/*.tgz"
- "*.tar.bz2"
- "**/*.tar.bz2"
- "*.tbz"
- "**/*.tbz"
- "*.tar.xz"
- "**/*.tar.xz"
- "*.txz"
- "**/*.txz"
- "*.tar.zst"
- "**/*.tar.zst"
- "*.tzst"
- "**/*.tzst"

# Caches
- ".cache/"
- ".cache"
- "**/.cache/"
- ".npm/"
- ".npm"
- "**/.npm/"
- ".cargo/registry/"
- ".cargo/registry"
- "**/.cargo/registry/"
- ".local/share/Trash/"
- ".local/share/Trash"
- "**/.local/share/Trash/"
- ".thumbnails/"
- ".thumbnails"
- "**/.thumbnails/"
- ".nv/"
- ".nv"
- "**/.nv/"
# RubyGems compact index cache
- ".bundle/cache/compact_index/rubygems.org.*"
- ".bundle/cache/compact_index/rubygems.org.*/*"
- "**/.bundle/cache/compact_index/rubygems.org.*"
- "**/.bundle/cache/compact_index/rubygems.org.*/*"


# Python & virtualenv
- "__pycache__/"
- "__pycache__"
- "**/__pycache__/"
- ".mypy_cache/"
- ".mypy_cache"
- "**/.mypy_cache/"
- ".pytest_cache/"
- ".pytest_cache"
- "**/.pytest_cache/"
- ".tox/"
- ".tox"
- "**/.tox/"
- ".venv/"
- ".venv"
- "**/.venv/"
- "venv/"
- "venv"
- "**/venv/"
- ".env/"
- ".env"
- "**/.env/"
- "env/"
- "env"
- "**/env/"

# git
- ".git/"
- ".git"
- "**/.git/"

# Node.js
- "node_modules/"
- "node_modules"
- "**/node_modules/"

# Rust
- "target/"
- "target"
- "**/target/"

# Java / Maven
- ".gradle/"
- ".gradle"
- "**/.gradle/"
- "build/"
- "build"
- "**/build/"

# Go
- "go/pkg/"
- "go/pkg"
- "**/go/pkg/"
- "go/bin/"
- "go/bin"
- "**/go/bin/"

# Compiled stuff
- "*.pyc"
- "**/*.pyc"
- "*.pyo"
- "**/*.pyo"
- "*.o"
- "**/*.o"
- "*.so"
- "**/*.so"
- "*.a"
- "**/*.a"
- "*.class"
- "**/*.class"
- "*.swp"
- "**/*.swp"

# Temp files
- "*.tmp"
- "**/*.tmp"
- "*.log"
- "**/*.log"
- "*~"
- "**/*~"

# Editor/IDE garbage
- ".idea/"
- ".idea"
- "**/.idea/"
- ".vscode/"
- ".vscode"
- "**/.vscode/"
- ".DS_Store"
- "**/.DS_Store"
- ".directory"
- "**/.directory"
- ".goutputstream-*"
- "**/.goutputstream-*"

# Downloads
- "Downloads/"
- "Downloads"
- "**/Downloads/"
- ".local/share/RecentDocuments/"
- ".local/share/RecentDocuments"
- "**/.local/share/RecentDocuments/"

# Trash / deleted files
- ".local/share/Trash/"
- ".local/share/Trash"
- "**/.local/share/Trash/"
- ".Trash*/"
- "**/.Trash*/"

# Snap / Flatpak cache stuff
- "snap/"
- "snap"
- "**/snap/"
- ".var/app/"
- ".var/app"
- "**/.var/app/"

# Mounts (if any inside home)
- "mnt/"
- "mnt"
- "**/mnt/"
- "media/"
- "media"
- "**/media/"
- "run/"
- "run"
- "**/run/"

# Containers
- ".docker/"
- ".docker"
- "**/.docker/"
- ".local/share/containers/"
- ".local/share/containers"
- "**/.local/share/containers/"
- ".local/share/flatpak/"
- ".local/share/flatpak"
- "**/.local/share/flatpak/"

# Image files
- "*.iso"
- "**/*.iso"
- "*.img"
- "**/*.img"
- "*.bin"
- "**/*.bin"
- "*.nrg"
- "**/*.nrg"
- "*.mdf"
- "**/*.mdf"
- "*.toast"
- "**/*.toast"
- "*.dmg"
- "**/*.dmg"

# Virtual machine disk formats
- "*.vdi"
- "**/*.vdi"
- "*.vmdk"
- "**/*.vmdk"
- "*.qcow2"
- "**/*.qcow2"
- "*.vhd"
- "**/*.vhd"
- "*.vhdx"
- "**/*.vhdx"