# configure the drives and buckets that appear in the dashboard

drives:
  - "/media/jim2/backupdrive"
  - "/"

s3_buckets:
  - "lampapps-jabs1"
  - "lampapps-jabs2"
  - "lampapps-jabs3"
  - "lampapps-jabs_dev"
  - "lampapps-backup"
 