monitored_targets:
  - name: "Pi"
    url: "http://192.168.1.28:5000/api/heartbeat"
    type: "jabs"
  - name: "Lampapps Website"
    url: "https://lampapps.com"
    type: "web"
    expect_text: "The Guide for Building a Business Website"
  - name: "JOF Gallery"
    url: "https://jof.gallery"
    type: "web"
    expect_text: "gallery"
  - name: "Jim-imac"
    url: "http://192.168.1.15:5000/api/heartbeat"
    type: "jabs"