# Example config file with minimal settings and comments.

job_name: "Example Name"  # The name of the backup job (used for logging and organization)
source: "/path/to/source" # The source directory to back up

schedules:
  - cron: "0 2 * * 0"    # Runs at 2:00 AM, every Sunday
    type: "full"         # full, diff, or incremental
    enabled: false       # true or false

  - cron: "0 2 * * 1-6"  # Runs at 2:00 AM, Monday to Saturday
    type: "incremental"  # full, diff, or incremental          
    enabled: false 

# Uncomment below to override Global Configuration if desired. See job.yaml for more
#encryption: 
  #enabled: false          # true or false, false can be overridden by CLI
#aws:
  #enabled: false          # true or false, false can be overridden by CLI

# exclude:
#  - "Pictures/"
